---
- name: Check the Switch Version
  hosts: switches
  gather_facts: yes
  vars:
    ops_debug: no
    cli:
      username: "{{ ops_username }}"
      password: "{{ ops_password }}"
      host: "{{ ansible_host }}"
      port: "{{ ansible_port }}"
    expected: OpenSwitch
  tasks:
    - name: show version CLI
      ops_command:
        commands:
          - show version
        provider: "{{ cli }}"
        waitfor:
          - "result[0] contains {{ expected }}"
        interval: 1
        retries: 2
      register: result
    - name: debug the result
      debug: var=result
      when: ops_debug

- name: Spine configuration
  hosts: spines
  gather_facts: no
  vars:
    ops_debug: yes
  roles:
    - role: switch
  ignore_errors: yes

- name: Leaves configuration
  hosts: leaves
  gather_facts: no
  vars:
    ops_debug: yes
  roles:
    - role: switch

